# Generated by Django 3.1 on 2020-08-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog_number', models.CharField(max_length=256)),
                ('semester', models.CharField(choices=[('f', 'fall'), ('s', 'spring')], default='f', max_length=1)),
                ('year', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=256)),
            ],
        ),
    ]
